### ISSUE TITLE
Vulnerability issue due to the tar package. https://npmjs.com/advisories/803  

### ISSUE THREAD

**Issue by nicolam1** [janeasystems/nodejs-mobile-gyp#6]
I tried locally to upgrade the tar package to ^4.4.2 and everything seems to be working the same. I was gonna create a PR but not enough permission. Could you upgrade the tar package?

**Comment by jaimecbernardo** [comment]
Hi @nicolam1 ,
Thank you. There was a PR open for this issue, which has been merged: https://github.com/janeasystems/nodejs-mobile-gyp/pull/5
We'll make a release with it soon.

**Comment by jaimecbernardo** [comment]
It's been released on 0.3.1 :  https://www.npmjs.com/package/nodejs-mobile-gyp/v/0.3.1
